<div class="modular-row callout home-extensions">
    <div class="max-width">
        <h2 class="title">Magento 2 Extensions</h2>

        <div class="extensions">
            <div class="extension">
                <div id="magento_extensions_list" class="extension-wrapper">
                    <a href="/magento2-extensions/google-tag-manager">
                        <div class="image">
                            <img title="Google Tag Manager" alt="Google Tag Manager" src="https://www.pronkoconsulting.com/images/8/c/1/9/0/8c19042364cdf1978da2e46284d7c10bde1ef312-pronko-google-tag-manager-magento-2.jpeg">
                        </div>

                        <h3 class="extension-title">
                            Google Tag Manager
                        </h3>
                    </a>

                    <div class="extension-container">
                        <div class="ext-price" style="">$49.99</div>
                    </div>
                </div>
            </div>
            <div class="extension">
                <div id="magento_extensions_list" class="extension-wrapper">
                    <a href="/magento2-extensions/converge-virtual-merchant">
                        <div class="image">
                            <img title="Converge Elavon" alt="Converge Elavon" src="https://www.pronkoconsulting.com/images/c/e/e/4/2/cee424d580c1f4603843e013e06e27f2d124e8c0-pronko-converge-virtual-merchant-magento-2.png">
                        </div>

                        <h3 class="extension-title">
                            Converge Elavon
                        </h3>
                    </a>

                    <div class="extension-container">
                        <div class="module-reviews-summary">
                            <div class="rating-summary">
                                <div class="rating-result rating-small" title="100%">
                                    <span style="width:100%"><span><span>5</span> of <span>5</span></span></span>
                                </div>
                                <a href="" class="rating-count">(7)</a>
                            </div>
                        </div>
                        <div class="ext-price" style="">$449</div>
                    </div>
                </div>
            </div>
            <div class="extension">
                <div id="magento_extensions_list" class="extension-wrapper">
                    <a href="/magento2-extensions/realex-payments">
                        <div class="image">
                            <img title="Realex Payments" alt="Realex Payments" src="https://www.pronkoconsulting.com/images/a/6/8/3/2/a6832bac0d7fe17288a558b843873271a8f67360-pronko-realex-payments-magento-2.png">
                        </div>

                        <h3 class="extension-title">
                            Realex Payments
                        </h3>
                    </a>

                    <div class="extension-container">
                        <div class="module-reviews-summary">
                            <div class="rating-summary">
                                <div class="rating-result rating-small" title="100%">
                                    <span style="width:100%"><span><span>5</span> of <span>5</span></span></span>
                                </div>
                                <a href="" class="rating-count">(3)</a>
                            </div>
                        </div>
                        <div class="ext-price" style="">$499</div>
                    </div>
                </div>
            </div>
            <div class="extension">
                <div id="magento_extensions_list" class="extension-wrapper">
                    <a href="/magento2-extensions/realex-payments">
                        <div class="image">
                            <img title="Realex Payments" alt="Realex Payments" src="https://www.pronkoconsulting.com/images/a/6/8/3/2/a6832bac0d7fe17288a558b843873271a8f67360-pronko-realex-payments-magento-2.png">
                        </div>

                        <h3 class="extension-title">
                            Realex Payments
                        </h3>
                    </a>

                    <div class="extension-container">
                        <div class="module-reviews-summary">
                            <div class="rating-summary">
                                <div class="rating-result rating-small" title="100%">
                                    <span style="width:100%"><span><span>5</span> of <span>5</span></span></span>
                                </div>
                                <a href="" class="rating-count">(3)</a>
                            </div>
                        </div>
                        <div class="ext-price" style="">$499</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="button-container">
            <a href="/magento2-extensions" class="button action large">All Magento 2 Extensions</a>
        </div>
    </div>
</div>