<div class="modular-row callout home-extensions">
    <div class="max-width">
        <h2 class="title">Magento 2 Extensions</h2>

        <div class="extensions">
            <div class="extension">
                <div class="extension-wrapper">
                    <a href="/magento2-extensions/converge-virtual-merchant">
                        <div class="image">
                            <img title="Converge Elavon" alt="Converge Elavon" src="https://www.pronkoconsulting.com/images/c/e/e/4/2/cee424d580c1f4603843e013e06e27f2d124e8c0-pronko-converge-virtual-merchant-magento-2.png">
                        </div>

                        <h3 class="extension-title">
                            Converge Elavon
                        </h3>
                    </a>

                    <div class="module-reviews-summary">
                        <div class="rating-summary">
                            <div class="rating-result rating-small" title="100%">
                                <span style="width:100%"><span><span>5</span> of <span>5</span></span></span>
                            </div>
                            <a href="" class="rating-count">(7)</a>
                        </div>
                    </div>
                    <p class="extension-summary">Flexible, secure and cost affective payment solution for your eCommerce website</p>

                </div>
            </div>
            <div class="extension">
                <div class="extension-wrapper">
                    <a href="/magento2-extensions/elavon-payment">
                        <div class="image">
                            <img title="Elavon Payment" alt="Elavon Payment" src="https://www.pronkoconsulting.com/images/6/4/a/9/5/64a95e0d03ee2a138392d56750fa38c901a73fb2-pronko-elavon-payment-magento-2.png">
                        </div>

                        <h3 class="extension-title">
                            Elavon Payment
                        </h3>
                    </a>

                    <div class="module-reviews-summary">
                        <div class="rating-summary">
                            <div class="rating-result rating-small" title="100%">
                                <span style="width:100%"><span><span>5</span> of <span>5</span></span></span>
                            </div>
                            <a href="" class="rating-count">(1)</a>
                        </div>
                    </div>
                    <p class="extension-summary">Start accepting credit and debit payments online with Elavon eCommerce solutions right away</p>

                </div>
            </div>
            <div class="extension">
                <div class="extension-wrapper">
                    <a href="/magento2-extensions/realex-payments">
                        <div class="image">
                            <img title="Realex Payments" alt="Realex Payments" src="https://www.pronkoconsulting.com/images/a/6/8/3/2/a6832bac0d7fe17288a558b843873271a8f67360-pronko-realex-payments-magento-2.png">
                        </div>

                        <h3 class="extension-title">
                            Realex Payments
                        </h3>
                    </a>

                    <div class="module-reviews-summary">
                        <div class="rating-summary">
                            <div class="rating-result rating-small" title="100%">
                                <span style="width:100%"><span><span>5</span> of <span>5</span></span></span>
                            </div>
                            <a href="" class="rating-count">(3)</a>
                        </div>
                    </div>
                    <p class="extension-summary">Simple and secure online payment extension for Magento 2 that suits your eCommerce business</p>

                </div>
            </div>
        </div>

        <div class="button-container">
            <a href="/magento2-extensions" class="btn secondary">
                All Extensions
            </a>
        </div>

    </div>
</div>